# SemanticBGKOctoMap config

# Map topic, grid cell mininum resolution
topic: /occupied_cells_vis_array
resolution: 0.3
block_depth: 3 # Test-data octree depth (see Wang & Englot ICRA 2016)

# Kernel parameters
sf2: 10.0 # Actually sigma_0 in sparse kernel
ell: 0.3 # Length scale of the sparse kernel

# Sampling resolutions
free_resolution: 100.0 # Free space sampling resolution (0.5)
ds_resolution: 0.1 # Downsampling factor

# Free/Occupied Thresholds
#free_thresh: 0.4588235294117647
#occupied_thresh: 0.5294117647058824
occupied_thresh: 0.7
var_thresh: 0.09 # Threshold on variance to distinguish known/unknown

# BGK Inference positive and negative class prior pseudocounts
prior_A: 0.001 # Positive class (occupied)
prior_B: 0.001 # Negative class (unoccupied)
