# sim_unstructured config

# Information about range-finder data
max_range: 10 # Sensor max range (m)

# Bounds on map height
min_z: 0
max_z: 4.3

original_size: true
predict: false

nc: 14 # Number of classes
