# sim_unstructured config

# Information about range-finder data
max_range: -1 # Sensor max range (m)

# Bounds on map height
min_z: 0
max_z: 4.3

original_size: true
predict: false

nc: 15 # Number of classes
